In [3]:
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from hmmlearn import hmm


# Step 1: define markov chain states and transition matrix
* define all posible chain states
* sepcify transition probabilities 
* use this to later simulate markov chain

In [6]:
states = ["sunny","rainy"]

transition_matrix = np.array([[0.8,0.2],
                             [0.4,0.6]])

print("\nTransition Matrix")
print(transition_matrix)




Transition Matrix
[[0.8 0.2]
 [0.4 0.6]]


# Step 2: Simulate Markov Chain Sequence
* generate sequence of states from transition matrix
* state from an initial state
* randomly choose next states according to trannsition probabilities

In [ ]:
def simulate_markov_chain(start_state, n_steps=20):
    current_state = states.index(start_state)
    sequence = [start_state]
    for _ in range(n_steps):
        current_state = np.random.choice([0,1], p=transition_matrix[current_state])
        sequence.append(states[current_state])
    return sequence

mc_sequence = simulate_markov_chain('sunny',15)
print("\n Generated Markov Chain Sequence:")
print(mc_sequence)



 Generated Markov Chain Sequence:
['sunny', 'sunny', 'rainy', 'rainy', 'rainy', 'sunny', 'sunny', 'sunny', 'sunny', 'sunny', 'sunny', 'rainy', 'rainy', 'sunny', 'sunny', 'sunny']


# Step 3: Define HMM paramterers
* define hidden states and observations for HMM
* set initial state probabilities, transition matrix and emission matrix
* these paramters define the behavior of HMM

In [8]:
hidden_states = ["Hot", "Cold"]
observations = ["IceCream", "Coffee"]

model = hmm.MultinomialHMM(n_components=2, n_iter=50)
model.transmat_ = np.array([
    [0.7, 0.3],  
    [0.4, 0.6]    
])
model.emissionprob_ = np.array([
    [0.8, 0.2],  
    [0.3, 0.7]   
])
model.startprob_ = np.array([0.6, 0.4])

print("\nTransition Matrix (Hidden States):")
print(model.transmat_)
print("\nEmission Matrix:")
print(model.emissionprob_)

MultinomialHMM has undergone major changes. The previous version was implementing a CategoricalHMM (a special case of MultinomialHMM). This new implementation follows the standard definition for a Multinomial distribution (e.g. as in https://en.wikipedia.org/wiki/Multinomial_distribution). See these issues for details:
https://github.com/hmmlearn/hmmlearn/issues/335
https://github.com/hmmlearn/hmmlearn/issues/340



Transition Matrix (Hidden States):
[[0.7 0.3]
 [0.4 0.6]]

Emission Matrix:
[[0.8 0.2]
 [0.3 0.7]]
